export component Card inherits Rectangle {
    border-radius: 10px;
    border-width: 1px;
    border-color: #626262;

    in property <string> label: "Card";

    VerticalLayout {
        padding: 10px;
        spacing: 5px;
        VerticalLayout {
            spacing: 5px;
            alignment: start;
            Text {
                text: label;
                horizontal-alignment: right;
            }

            Rectangle {
                height: 1px;
                background: white;
            }
        }

        VerticalLayout {
            alignment: start;
            @children
        }
    }
}
