export global Theme {
    out property <color> bg: #1212126d;
    out property <color> fg: #ffffff;

    out property <color> alt-bg: #1f1f1f71;
    out property <color> alt-fg: #ffffff;

    out property <color> accent: #00bbff;

    out property <length> gap: 5px;
    out property <length> bor-r: 10px;

    out property <color> bor-c: #5555556c;
    // out property <color> bor-c: transparent;
}
